# Generated by Django 5.2.4 on 2025-07-19 19:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("documents", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentRequestResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "response",
                    models.CharField(
                        choices=[
                            ("approve", "Approve"),
                            ("decline", "Decline"),
                            ("request_info", "Request More Information"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField(blank=True, null=True)),
                ("responded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="documents.documentrequest",
                    ),
                ),
                (
                    "responder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="request_responses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shared_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Request Response",
                "verbose_name_plural": "Document Request Responses",
                "ordering": ["-responded_at"],
            },
        ),
        migrations.CreateModel(
            name="QRCodeShare",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "permission",
                    models.CharField(
                        choices=[("view", "View Only"), ("download", "Download")],
                        default="view",
                        max_length=20,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("max_views", models.PositiveIntegerField(default=1)),
                ("current_views", models.PositiveIntegerField(default=0)),
                (
                    "qr_code_image",
                    models.ImageField(blank=True, null=True, upload_to="qr_codes/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("revoked", "Revoked"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_qr_shares",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qr_shares",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "verbose_name": "QR Code Share",
                "verbose_name_plural": "QR Code Shares",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ShareNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("document_shared", "Document Shared"),
                            ("document_requested", "Document Requested"),
                            ("request_responded", "Request Responded"),
                            ("access_granted", "Access Granted"),
                            ("qr_accessed", "QR Code Accessed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="documents.document",
                    ),
                ),
                (
                    "document_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="documents.documentrequest",
                    ),
                ),
                (
                    "qr_share",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sharing.qrcodeshare",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="share_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Share Notification",
                "verbose_name_plural": "Share Notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ShareSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("session_token", models.CharField(max_length=255, unique=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("accessed_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("revoked", "Revoked"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "qr_share",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="sharing.qrcodeshare",
                    ),
                ),
            ],
            options={
                "verbose_name": "Share Session",
                "verbose_name_plural": "Share Sessions",
                "ordering": ["-accessed_at"],
            },
        ),
        migrations.CreateModel(
            name="SharingActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("qr_created", "QR Code Created"),
                            ("qr_accessed", "QR Code Accessed"),
                            ("document_shared", "Document Shared"),
                            ("document_requested", "Document Requested"),
                            ("request_responded", "Request Responded"),
                            ("access_granted", "Access Granted"),
                            ("access_revoked", "Access Revoked"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="documents.document",
                    ),
                ),
                (
                    "document_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="documents.documentrequest",
                    ),
                ),
                (
                    "qr_share",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sharing.qrcodeshare",
                    ),
                ),
                (
                    "share_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sharing.sharesession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sharing_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Sharing Activity",
                "verbose_name_plural": "Sharing Activities",
                "ordering": ["-created_at"],
            },
        ),
    ]
